### ISSUE TITLE
Tooltip on Teleports overlap

### ISSUE THREAD

**Issue by Imiona** [mBlinkii/mMediaTag#82]
Hey

The Tooltip for the Teleports overlaps with the Frame, is there a way to fix this? Its a little bit distracting. Thanks

![tooltip](https://github.com/mBlinkii/mMediaTag/assets/11210717/ebb395b0-7a33-4455-a567-5693244fa252)

**Comment by mBlinkii** [comment]
Hi Imiona,
I add a setting for the Tooltip Anchor under mMT > Datatext > Teleports > Tooltip anchor on cursor. 

https://github.com/mBlinkii/mMediaTag/compare/main...Development
https://github.com/mBlinkii/mMediaTag/archive/refs/heads/Development.zip

You can download mMediaTag & Tools Dev Version from the link above.

Dev versions of mMediaTag & Tools are under development and have recent changes, but are not yet ready to be released, usually due to testing or implementation in progress.

You will need to manually extract the ElvUI_mMediaTag and !mMT_MediaPack folders inside mMediaTag-Development/Addon into your addons folder to try it.
